services:
  db:
    # image: postgres:latest
    container_name: postgres-container-for-study
    build: .
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuser
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"

volumes:
  postgres_data:
